
title: shopizer-api
delegatePattern: true
useTags: true
#swaggerDocketConfig: true

importMappings:
  Address: com.salesmanager.shop.model.customer.address.Address
#  Address: com.salesmanager.shop.model.references.Address
  AddressLocation: com.salesmanager.shop.model.customer.address.AddressLocation
  AnonymousCustomer: com.salesmanager.shop.model.customer.AnonymousCustomer
  AuthenticationResponse: com.salesmanager.shop.store.security.AuthenticationResponse
  AuthenticationRequest: com.salesmanager.shop.store.security.AuthenticationRequest
  CartModificationException: com.salesmanager.shop.model.shoppingcart.CartModificationException
  CatalogEntity: com.salesmanager.shop.model.catalog.catalog.CatalogEntity
  CatalogEntryEntity: com.salesmanager.shop.model.catalog.catalog.CatalogEntryEntity
  Category: com.salesmanager.shop.model.catalog.category.Category
  CategoryDescription: com.salesmanager.shop.model.catalog.category.CategoryDescription
  CategoryEntity: com.salesmanager.shop.model.catalog.category.CategoryEntity
  Configs: com.salesmanager.shop.model.system.Configs
  ContactForm: com.salesmanager.shop.model.shop.ContactForm
  Content: com.salesmanager.shop.model.content.Content
  ContentDescriptionEntity: com.salesmanager.shop.model.content.ContentDescriptionEntity
  ContentEntity: com.salesmanager.shop.model.content.ContentEntity
  ContentFile: com.salesmanager.shop.model.content.ContentFile
  ContentFolder: com.salesmanager.shop.model.content.ContentFolder
  ContentImage: com.salesmanager.shop.model.content.ContentImage
  ContentName: com.salesmanager.shop.model.content.ContentName
  ContentPath: com.salesmanager.shop.model.content.ContentPath
  ContentSettings: com.salesmanager.shop.model.content.ContentSettings
  CountryEntity: com.salesmanager.shop.model.references.CountryEntity
  CreditCard: com.salesmanager.core.model.order.payment.CreditCard
  Currency: com.salesmanager.core.model.reference.currency.Currency
  Customer: com.salesmanager.shop.model.customer.Customer
  CustomerAttribute: com.salesmanager.shop.model.customer.attribute.CustomerAttribute
  CustomerAttributeEntity: com.salesmanager.shop.model.customer.attribute.CustomerAttributeEntity
  CustomerEntity: com.salesmanager.shop.model.customer.CustomerEntity
  CustomerOptin: com.salesmanager.shop.model.customer.optin.CustomerOptin
  CustomerOptinEntity: com.salesmanager.shop.model.customer.optin.CustomerOptinEntity
  CustomerOption: com.salesmanager.shop.model.customer.attribute.CustomerOption
  CustomerOptionDescription: com.salesmanager.shop.model.customer.attribute.CustomerOptionDescription
  CustomerOptionEntity: com.salesmanager.shop.model.customer.attribute.CustomerOptionEntity
  CustomerOptionValue: com.salesmanager.shop.model.customer.attribute.CustomerOptionValue
  CustomerOptionValueDescription: com.salesmanager.shop.model.customer.attribute.CustomerOptionValueDescription
  CustomerOptionValueEntity: com.salesmanager.shop.model.customer.attribute.CustomerOptionValueEntity
  CustomerPassword: com.salesmanager.shop.model.customer.CustomerPassword
  CustomerReviewEntity: com.salesmanager.shop.model.customer.CustomerReviewEntity
  DeliveryEntity: com.salesmanager.shop.model.customer.DeliveryEntity
  DimensionUnitOfMeasure: com.salesmanager.shop.model.references.DimensionUnitOfMeasure
  Entity: com.salesmanager.shop.model.entity.Entity
  Error: com.salesmanager.shop.store.api.exception.ErrorEntity
  EntityExists: com.salesmanager.shop.model.entity.EntityExists
  GroupEntity: com.salesmanager.shop.model.security.GroupEntity
  InventoryEntity: com.salesmanager.shop.model.catalog.product.inventory.InventoryEntity
  Language: com.salesmanager.core.model.reference.language.Language
  LightPersistableProduct: com.salesmanager.shop.model.catalog.product.LightPersistableProduct
  ListCriteria: com.salesmanager.shop.model.entity.ListCriteria
  Manufacturer: com.salesmanager.shop.model.catalog.manufacturer.Manufacturer
  ManufacturerDescription: com.salesmanager.shop.model.catalog.manufacturer.ManufacturerDescription
  ManufacturerEntity: com.salesmanager.shop.model.catalog.manufacturer.ManufacturerEntity
  MarketPlaceEntity: com.salesmanager.shop.model.marketplace.MarketPlaceEntity
  MeasureUnit: com.salesmanager.shop.model.references.MeasureUnit
  MerchantConfigEntity: com.salesmanager.shop.model.store.MerchantConfigEntity
  MerchantStoreBrand: com.salesmanager.shop.model.store.MerchantStoreBrand
  MerchantStoreEntity: com.salesmanager.shop.model.store.MerchantStoreEntity
  NamedEntity: com.salesmanager.shop.model.catalog.NamedEntity
  ObjectContent: com.salesmanager.shop.model.content.ObjectContent
  Optin: com.salesmanager.shop.model.system.Optin
  OptinEntity: com.salesmanager.shop.model.system.OptinEntity
  Order: com.salesmanager.shop.model.order.Order
  OrderApi: com.salesmanager.shop.model.order.OrderApi
  OrderAttribute: com.salesmanager.shop.model.order.OrderAttribute
  OrderEntity: com.salesmanager.shop.model.order.OrderEntity
  OrderProduct: com.salesmanager.shop.model.order.OrderProduct
  OrderProductEntity: com.salesmanager.shop.model.order.OrderProductEntity
  OrderTotal: com.salesmanager.shop.model.order.total.OrderTotal
  PasswordRequest: com.salesmanager.shop.store.security.PasswordRequest
  PaymentEntity: com.salesmanager.shop.model.order.transaction.PaymentEntity
  PermissionEntity: com.salesmanager.shop.model.security.PermissionEntity
  PersistableAddress: com.salesmanager.shop.model.references.PersistableAddress
  PersistableAnonymousOrderApi: com.salesmanager.shop.model.order.PersistableAnonymousOrderApi
  PersistableBrand: com.salesmanager.shop.model.store.PersistableBrand
  PersistableCatalog: com.salesmanager.shop.model.catalog.catalog.PersistableCatalog
  PersistableCatalogEntry: com.salesmanager.shop.model.catalog.catalog.PersistableCatalogEntry
  PersistableCategory: com.salesmanager.shop.model.catalog.category.PersistableCategory
  PersistableContent: com.salesmanager.shop.model.content.PersistableContent
  PersistableContentEntity: com.salesmanager.shop.model.content.PersistableContentEntity
  PersistableContentPage: com.salesmanager.shop.model.content.PersistableContentPage
  PersistableCustomer: com.salesmanager.shop.model.customer.PersistableCustomer
  PersistableCustomerAttribute: com.salesmanager.shop.model.customer.attribute.PersistableCustomerAttribute
  PersistableCustomerOptin: com.salesmanager.shop.model.customer.optin.PersistableCustomerOptin
  PersistableCustomerOption: com.salesmanager.shop.model.customer.attribute.PersistableCustomerOption
  PersistableCustomerOptionValue: com.salesmanager.shop.model.customer.attribute.PersistableCustomerOptionValue
  PersistableCustomerReview: com.salesmanager.shop.model.customer.PersistableCustomerReview
  PersistableGroup: com.salesmanager.shop.model.security.PersistableGroup
  PersistableImage: com.salesmanager.shop.model.catalog.product.PersistableImage
  PersistableInventory: com.salesmanager.shop.model.catalog.product.inventory.PersistableInventory
  PersistableManufacturer: com.salesmanager.shop.model.catalog.manufacturer.PersistableManufacturer
  PersistableMerchantStore: com.salesmanager.shop.model.shop.PersistableMerchantStore
#  PersistableMerchantStore: com.salesmanager.shop.model.store.PersistableMerchantStore
  PersistableOptin: com.salesmanager.shop.model.system.PersistableOptin
  PersistableOrder: com.salesmanager.shop.model.order.PersistableOrder
  PersistableOrderApi: com.salesmanager.shop.model.order.PersistableOrderApi
  PersistableOrderProduct: com.salesmanager.shop.model.order.PersistableOrderProduct
  PersistablePayment: com.salesmanager.shop.model.order.transaction.PersistablePayment
  PersistableProduct: com.salesmanager.shop.model.catalog.product.PersistableProduct
  PersistableProductAttribute: com.salesmanager.shop.model.catalog.product.attribute.PersistableProductAttribute
  PersistableProductOption: com.salesmanager.shop.model.catalog.product.attribute.PersistableProductOption
  PersistableProductOptionEntity: com.salesmanager.shop.model.catalog.product.attribute.api.PersistableProductOptionEntity
  PersistableProductOptionValue: com.salesmanager.shop.model.catalog.product.attribute.PersistableProductOptionValue
  PersistableProductOptionValueEntity: com.salesmanager.shop.model.catalog.product.attribute.api.PersistableProductOptionValueEntity
  PersistableProductPrice: com.salesmanager.shop.model.catalog.product.PersistableProductPrice
  PersistableProductReview: com.salesmanager.shop.model.catalog.product.PersistableProductReview
  PersistableShoppingCartItem: com.salesmanager.shop.model.shoppingcart.PersistableShoppingCartItem
  PersistableTransaction: com.salesmanager.shop.model.order.transaction.PersistableTransaction
  PersistableUser: com.salesmanager.shop.model.user.PersistableUser
  Product: com.salesmanager.shop.model.catalog.product.Product
  ProductAttribute: com.salesmanager.shop.model.catalog.product.attribute.ProductAttribute
  ProductAttributeEntity: com.salesmanager.shop.model.catalog.product.attribute.api.ProductAttributeEntity
  ProductAttributeValueDescription: com.salesmanager.shop.model.catalog.product.attribute.ProductAttributeValueDescription
  ProductDescription: com.salesmanager.shop.model.catalog.product.ProductDescription
  ProductEntity: com.salesmanager.shop.model.catalog.product.ProductEntity
  ProductGroup: com.salesmanager.shop.model.catalog.product.group.ProductGroup
  ProductList: com.salesmanager.shop.model.catalog.ProductList
  ProductOption: com.salesmanager.shop.model.catalog.product.attribute.ProductOption
  ProductOptionDescription: com.salesmanager.shop.model.catalog.product.attribute.ProductOptionDescription
  ProductOptionEntity: com.salesmanager.shop.model.catalog.product.attribute.ProductOptionEntity
  ProductOptionValue: com.salesmanager.shop.model.catalog.product.attribute.ProductOptionValue
  ProductOptionValueDescription: com.salesmanager.shop.model.catalog.product.attribute.ProductOptionValueDescription
  ProductOptionValueEntity: com.salesmanager.shop.model.catalog.product.attribute.api.ProductOptionValueEntity
  ProductPrice: com.salesmanager.shop.model.catalog.product.ProductPrice
  ProductPriceDescription: com.salesmanager.shop.model.catalog.product.ProductPriceDescription
  ProductPriceEntity: com.salesmanager.shop.model.catalog.product.ProductPriceEntity
  ProductReviewEntity: com.salesmanager.shop.model.catalog.product.ProductReviewEntity
  ProductSpecification: com.salesmanager.shop.model.catalog.product.ProductSpecification
  ReadableAddress: com.salesmanager.shop.model.references.ReadableAddress
  ReadableAudit: com.salesmanager.shop.model.entity.ReadableAudit
  ReadableAuditable: com.salesmanager.shop.model.entity.ReadableAuditable
  ReadableBrand: com.salesmanager.shop.model.store.ReadableBrand
  ReadableCatalog: com.salesmanager.shop.model.catalog.catalog.ReadableCatalog
  ReadableCatalogEntry: com.salesmanager.shop.model.catalog.catalog.ReadableCatalogEntry
  ReadableCatalogEntryList: com.salesmanager.shop.model.catalog.catalog.ReadableCatalogEntryList
  ReadableCatalogList: com.salesmanager.shop.model.catalog.catalog.ReadableCatalogList
  ReadableCategory: com.salesmanager.shop.model.catalog.category.ReadableCategory
  ReadableCategoryFull: com.salesmanager.shop.model.catalog.category.ReadableCategoryFull
  ReadableCategoryList: com.salesmanager.shop.model.catalog.category.ReadableCategoryList
  ReadableContent: com.salesmanager.shop.model.content.ReadableContent
  ReadableContentBox: com.salesmanager.shop.model.content.ReadableContentBox
  ReadableContentEntity: com.salesmanager.shop.model.content.ReadableContentEntity
  ReadableContentFull: com.salesmanager.shop.model.content.ReadableContentFull
  ReadableContentObject: com.salesmanager.shop.model.content.ReadableContentObject
  ReadableContentPage: com.salesmanager.shop.model.content.ReadableContentPage
  ReadableCountry: com.salesmanager.shop.model.references.ReadableCountry
  ReadableCustomer: com.salesmanager.shop.model.customer.ReadableCustomer
  ReadableCustomerAttribute: com.salesmanager.shop.model.customer.attribute.ReadableCustomerAttribute
  ReadableCustomerList: com.salesmanager.shop.populator.customer.ReadableCustomerList
  ReadableCustomerOption: com.salesmanager.shop.model.customer.attribute.ReadableCustomerOption
  ReadableCustomerOptionValue: com.salesmanager.shop.model.customer.attribute.ReadableCustomerOptionValue
  ReadableCustomerReview: com.salesmanager.shop.model.customer.ReadableCustomerReview
  ReadableDelivery: com.salesmanager.shop.model.customer.ReadableDelivery
  ReadableEntity: com.salesmanager.shop.model.entity.ReadableEntity
  ReadableGroup: com.salesmanager.shop.model.security.ReadableGroup
#  ReadableImage: com.salesmanager.shop.model.catalog.product.ReadableImage
  ReadableImage: com.salesmanager.shop.model.content.ReadableImage
  ReadableInventory: com.salesmanager.shop.model.catalog.product.inventory.ReadableInventory
  ReadableInventoryList: com.salesmanager.shop.model.catalog.product.inventory.ReadableInventoryList
  ReadableList: com.salesmanager.shop.model.entity.ReadableList
  ReadableManufacturer: com.salesmanager.shop.model.catalog.manufacturer.ReadableManufacturer
  ReadableManufacturerFull: com.salesmanager.shop.model.catalog.manufacturer.ReadableManufacturerFull
  ReadableManufacturerList: com.salesmanager.shop.model.catalog.manufacturer.ReadableManufacturerList
  ReadableMarketPlace: com.salesmanager.shop.model.marketplace.ReadableMarketPlace
  ReadableMerchantStore: com.salesmanager.shop.model.store.ReadableMerchantStore
  ReadableMerchantStoreList: com.salesmanager.shop.model.store.ReadableMerchantStoreList
  ReadableOptin: com.salesmanager.shop.model.system.ReadableOptin
  ReadableOrder: com.salesmanager.shop.model.order.ReadableOrder
  ReadableOrderApi: com.salesmanager.shop.model.order.ReadableOrderApi
  ReadableOrderList: com.salesmanager.shop.model.order.ReadableOrderList
  ReadableOrderProduct: com.salesmanager.shop.model.order.ReadableOrderProduct
  ReadableOrderProductAttribute: com.salesmanager.shop.model.order.ReadableOrderProductAttribute
  ReadableOrderProductDownload: com.salesmanager.shop.model.order.ReadableOrderProductDownload
  ReadableOrderTotal: com.salesmanager.shop.model.order.total.ReadableOrderTotal
  ReadableOrderTotalSummary: com.salesmanager.shop.model.order.ReadableOrderTotalSummary
  ReadablePayment: com.salesmanager.shop.model.order.transaction.ReadablePayment
  ReadablePermission: com.salesmanager.shop.model.security.ReadablePermission
  ReadableProduct: com.salesmanager.shop.model.catalog.product.ReadableProduct
  ReadableProductAttribute: com.salesmanager.shop.model.catalog.product.attribute.ReadableProductAttribute
  ReadableProductAttributeEntity: com.salesmanager.shop.model.catalog.product.attribute.api.ReadableProductAttributeEntity
  ReadableProductAttributeList: com.salesmanager.shop.model.catalog.product.attribute.api.ReadableProductAttributeList
  ReadableProductAttributeValue: com.salesmanager.shop.model.catalog.product.attribute.ReadableProductAttributeValue
  ReadableProductFull: com.salesmanager.shop.model.catalog.product.ReadableProductFull
  ReadableProductList: com.salesmanager.shop.model.catalog.product.ReadableProductList
  ReadableProductOption: com.salesmanager.shop.model.catalog.product.attribute.ReadableProductOption
  ReadableProductOptionEntity: com.salesmanager.shop.model.catalog.product.attribute.api.ReadableProductOptionEntity
  ReadableProductOptionFull: com.salesmanager.shop.model.catalog.product.attribute.api.ReadableProductOptionFull
  ReadableProductOptionList: com.salesmanager.shop.model.catalog.product.attribute.api.ReadableProductOptionList
  ReadableProductOptionValue: com.salesmanager.shop.model.catalog.product.attribute.ReadableProductOptionValue
  ReadableProductOptionValueEntity: com.salesmanager.shop.model.catalog.product.attribute.api.ReadableProductOptionValueEntity
  ReadableProductOptionValueFull: com.salesmanager.shop.model.catalog.product.attribute.api.ReadableProductOptionValueFull
  ReadableProductOptionValueList: com.salesmanager.shop.model.catalog.product.attribute.api.ReadableProductOptionValueList
  ReadableProductPrice: com.salesmanager.shop.model.catalog.product.ReadableProductPrice
  ReadableProductPriceFull: com.salesmanager.shop.model.catalog.product.ReadableProductPriceFull
  ReadableProductReview: com.salesmanager.shop.model.catalog.product.ReadableProductReview
  ReadableProductType: com.salesmanager.shop.model.catalog.product.type.ReadableProductType
  ReadableProductVariant: com.salesmanager.shop.model.catalog.product.attribute.ReadableProductVariant
  ReadableProductVariantValue: com.salesmanager.shop.model.catalog.product.attribute.ReadableProductVariantValue
  ReadableSelectedProductVariant: com.salesmanager.shop.model.catalog.product.attribute.ReadableSelectedProductVariant
  ReadableShippingSummary: com.salesmanager.shop.model.order.shipping.ReadableShippingSummary
  ReadableShopOrder: com.salesmanager.shop.model.order.ReadableShopOrder
  ReadableShoppingCart: com.salesmanager.shop.model.shoppingcart.ReadableShoppingCart
  ReadableShoppingCartAttribute: com.salesmanager.shop.model.shoppingcart.ReadableShoppingCartAttribute
  ReadableShoppingCartAttributeOption: com.salesmanager.shop.model.shoppingcart.ReadableShoppingCartAttributeOption
  ReadableShoppingCartAttributeOptionValue: com.salesmanager.shop.model.shoppingcart.ReadableShoppingCartAttributeOptionValue
  ReadableShoppingCartItem: com.salesmanager.shop.model.shoppingcart.ReadableShoppingCartItem
  ReadableTotal: com.salesmanager.shop.model.order.total.ReadableTotal
  ReadableTransaction: com.salesmanager.shop.model.order.transaction.ReadableTransaction
  ReadableUser: com.salesmanager.shop.model.user.ReadableUser
  ReadableUserList: com.salesmanager.shop.model.user.ReadableUserList
  ReadableZone: com.salesmanager.shop.model.references.ReadableZone
  RelatedProduct: com.salesmanager.shop.model.catalog.product.RelatedProduct
  RentalOwner: com.salesmanager.shop.model.catalog.product.RentalOwner
  ResourceUrlAccess: com.salesmanager.shop.model.entity.ResourceUrlAccess
  ResponseEntity: org.springframework.http.ResponseEntity
  SearchProductList: com.salesmanager.shop.model.catalog.SearchProductList
  SearchProductRequest: com.salesmanager.shop.model.catalog.SearchProductRequest
  SecuredCustomer: com.salesmanager.shop.model.customer.SecuredCustomer
  SecuredShopPersistableCustomer: com.salesmanager.shop.model.customer.SecuredShopPersistableCustomer
  ServiceEntity: com.salesmanager.shop.model.entity.ServiceEntity
  ShippingOption: com.salesmanager.core.model.shipping.ShippingOption
  ShopEntity: com.salesmanager.shop.model.entity.ShopEntity
  ShopOrder: com.salesmanager.shop.model.order.ShopOrder
  ShoppingCartAttribute: com.salesmanager.shop.model.shoppingcart.ShoppingCartAttribute
  ShoppingCartData: com.salesmanager.shop.model.shoppingcart.ShoppingCartData
  ShoppingCartEntity: com.salesmanager.shop.model.shoppingcart.ShoppingCartEntity
  ShoppingCartItem: com.salesmanager.shop.model.shoppingcart.ShoppingCartItem
  SizeReferences: com.salesmanager.shop.model.references.SizeReferences
  TransactionEntity: com.salesmanager.shop.model.order.transaction.TransactionEntity
  UniqueEntity: com.salesmanager.shop.model.entity.UniqueEntity
  User: com.salesmanager.shop.model.user.User
  UserAlreadyExistException: com.salesmanager.shop.model.customer.UserAlreadyExistException
  UserEntity: com.salesmanager.shop.model.user.UserEntity
  UserPassword: com.salesmanager.shop.model.user.UserPassword
  ValueList: com.salesmanager.shop.model.entity.ValueList
  WeightUnit: com.salesmanager.shop.model.references.WeightUnit
  WeightUnitOfMeasure: com.salesmanager.shop.model.references.WeightUnitOfMeasure
  ZoneEntity: com.salesmanager.shop.model.references.ZoneEntity
